### ISSUE TITLE
Reloading GUI page gives error

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-docker#10]
Then i refreash the browser using reload on chrome on the following page:
http://ipaddress:8088/player

it then loads the page below with error 

http://ipaddress/player/

**Comment by jb-alvarado** [comment]
This issue belongs to docker.

It is not really a bug. You need to use a proxy to redirect port 80 or 443 to 8088, in production you really should use ssl. When you only testing on your local machine you can also change the port in docker compose file to 80.

**Comment by edwoodza** [comment]
> 
> 
> This issue belongs to docker.
> 
> It is not really a bug. You need to use a proxy to redirect port 80 or 443 to 8088, in production you really should use ssl. When you only testing on your local machine you can also change the port in docker compose file to 80.

ok. good to know.
yet another reason to not use docker lol
