### ISSUE TITLE
Support SRT out?

### ISSUE THREAD

**Issue by jengajenga** [ffplayout/ffplayout-docker#11]
Hello @jb-alvarado ,

I've been trying out the playout and I have so far been able to receive the rtmp via vlc.

However when I change this to HLS or to SRT, I am unable to pull it.

![ffplay- srt](https://user-images.githubusercontent.com/65451390/104835600-cd81e180-58b8-11eb-8f7d-cec796e9782a.PNG)

Is there something I am doing wrong? Also, I don't understand 
1. where to put the 'output' file
2. which folder to put it in
3. what configurations to put in
4. what format - is it similar to the srs.conf file? Is there a sample?

Thank you.

**Comment by jb-alvarado** [comment]
Hello,
when you using the normal default setup, you can pull hls with: http://[DNS/IP:8088]/live/tv.m3u8. For SRT you need a server to stream to, srs will not work for that, here you have to edit the stream_output with the correct target. In this mode you have no preview in the frontend.

The seconds HLS output option I would script at the moment, so you can ignore the hls_output parameter in config. Just use the HLS option from SRS, that is the most stable and tested option.

**Comment by jengajenga** [comment]
> Hello,
> when you using the normal default setup, you can pull hls with: http://[DNS/IP:8088]/live/tv.m3u8. For SRT you need a server to stream to, srs will not work for that, here you have to edit the stream_output with the correct target. In this mode you have no preview in the frontend.
> 
> The seconds HLS output option I would script at the moment, so you can ignore the hls_output parameter in config. Just use the HLS option from SRS, that is the most stable and tested option.

Thanks. I have an srt server target which I am trying to send the stream to. I don't see it at the server because it's not sending it out.

**Comment by jb-alvarado** [comment]
With srt I have no experience, so I can not give your support for that. But you can examine the logs and see what it says there.

**Comment by edwoodza** [comment]
@jengajenga  what notation wee you using for the SRT? 
srt://server:port?

**Comment by jengajenga** [comment]
> @jengajenga what notation wee you using for the SRT?
> srt://server:port?

hi

yes srt://server-ip:port?streamid=this

**Comment by edwoodza** [comment]
Yeah I tried the same and also did not connect to SRT server.
Not much in logs either.

Is the SRT support via ffmpeg (assuming the version of ffmpeg has it in)

Or native SRT?

**Comment by jengajenga** [comment]
> Yeah I tried the same and also did not connect to SRT server.
> Not much in logs either.
> 
> Is the SRT support via ffmpeg (assuming the version of ffmpeg has it in)
> 
> Or native SRT?

I think it is in the ffmpeg support. the SRS server 3.0 doesn't support srt.

but alvarado says he's working on multiple outputs so i think he will consider this.

**Comment by edwoodza** [comment]
Yeah. I have a SRT server of my own I was pushing to.
But not had success yet
