### ISSUE TITLE
Playout not "playing"

### ISSUE THREAD

**Issue by jengajenga** [ffplayout/ffplayout-docker#12]
Hi @jb-alvarado 

I am also facing this issue. I have set the playout to play from 'storage' and not playlist because I am not to sure how to do the playlist (instructions aren't very clear to me).

If you see the image, this is what I get

![playout](https://user-images.githubusercontent.com/65451390/104835715-82b49980-58b9-11eb-9437-f28460b9b15c.PNG)

So the buttons don't work, and only the player is able to play.

What steps do I take to correct it?

Thank you

**Comment by jb-alvarado** [comment]
On the left side you have your file browser, and the right side is you playlist. You can drag files from browser to playlist, and when you have your playlist full you can save it with the buttons down right.

**Comment by jengajenga** [comment]
> On the left side you have your file browser, and the right side is you playlist. You can drag files from browser to playlist, and when you have your playlist full you can save it with the buttons down right.

Thanks for responding. I have been doing that. But this message comes up.

![media_source](https://user-images.githubusercontent.com/65451390/104838775-26a84000-58ce-11eb-9aaf-fbefb7e5418f.PNG)

When I press the green/red/orange/yellow buttons, nothing happens. But when I press the player, the clip plays.

So I am not sure what to do.

**Comment by jengajenga** [comment]
And I have removed the first video and put another one. But the player keeps playing the first video even I have removed it. Even with a different browser. Very strange.

**Comment by jb-alvarado** [comment]
You can only preview files which are supported by the browser. MKV is not supported by any browser. For playout you can use it, but not for previewing.

The green/red/orange/yellow buttons are for controlling the streaming output, when you hover them, you get a info for what they are.
