### ISSUE TITLE
One Success! One Failure!

### ISSUE THREAD

**Issue by jengajenga** [ffplayout/ffplayout-docker#13]
@jb-alvarado ,

So i can confirm that my stream - rtmp - has reached my server. When I click the green big play button, I am able to publish and push even as the logging shows. So that one is successful.

Now, I am unfortunately unable to see any indication in the GUI that there is streaming. 

![no_indication](https://user-images.githubusercontent.com/65451390/104855076-a3add680-591b-11eb-90dc-f698efdb05c6.PNG)

How come these numbers and progress bar remains static? They do not update.

Help. Thank you.

**Comment by jengajenga** [comment]
this is my playlist

![no_indication](https://user-images.githubusercontent.com/65451390/104855199-6e55b880-591c-11eb-801a-8007d7c6e995.PNG)

**Comment by jb-alvarado** [comment]
In your case you see, that the stream is running on the green glowing border around the play button. The progress bar and timecode works only correctly in playlist mode with a setted **day_start** and **length**: 24:00:00

**Comment by jengajenga** [comment]
> In your case you see, that the stream is running on the green glowing border around the play button. The progress bar and timecode works only correctly in playlist mode with a setted **day_start** and **length**: 24:00:00

Ok.

So what format is the playlist? is it a .csv file or what do i put? When I open the playlist folder, i see Readme.md which says "playlists goes here.The folder structure is created automatically."

How do you make a playlist?

**Comment by jb-alvarado** [comment]
The playlist is a json format, in that structure: [json-playlist-example](https://github.com/ffplayout/ffplayout-engine/blob/master/README.md#json-playlist-example)

We have self programmed media and playlist management tool, with that we make our playlists and with ffplayout-api we transfer them to the playout.

**Comment by jengajenga** [comment]
> The playlist is a json format, in that structure: [json-playlist-example](https://github.com/ffplayout/ffplayout-engine/blob/master/README.md#json-playlist-example)
> 
> We have self programmed media and playlist management tool, with that we make our playlists and with ffplayout-api we transfer them to the playout.

Thank you again.

Where is the self programmed media and playlist management tool?

**Comment by jb-alvarado** [comment]
Is not open source, I have explain it a bit here: https://github.com/ffplayout/ffplayout-frontend/issues/46

**Comment by jengajenga** [comment]
> Is not open source, I have explain it a bit here: [ffplayout/ffplayout-frontend#46](https://github.com/ffplayout/ffplayout-frontend/issues/46)

I have seen. Thanks.

So for us to make a playlist, we have to write it manually one by one like this format : https://github.com/ffplayout/ffplayout-engine/blob/master/README.md#json-playlist-example

**Comment by jb-alvarado** [comment]
No, you can drag die files in the GUI to the playlist area and save them there.

**Comment by jengajenga** [comment]
> No, you can drag the files in the GUI to the playlist area and save them there.
> 
> Here I have also a example script, which you can modify to your needs: https://github.com/ffplayout/ffplayout-engine/blob/master/docs/gen_playlist_from_subfolders.sh

Ok. Let me play around with it for some time and see what happens.

Thanks.
