### ISSUE TITLE
ffplayer-frontend image fails to build

### ISSUE THREAD

**Issue by spencerhughes** [ffplayout/ffplayout-docker#16]
**Describe the bug**
ffplayer-frontend fails to build because of missing python binary. If you add python3 to the Dockerfile, it fails because it is missing make, and if you install make it failes with a file not found error.

**To Reproduce**
1. Clone repo
2. Run `docker-compose build`
3. See error

**Expected behavior**
Container would build successfully.

**Logging**

Before installing python3
[before-python3.txt](https://github.com/ffplayout/ffplayout-docker/files/7664803/before-python3.txt)

After installing python3
[after-python3.txt](https://github.com/ffplayout/ffplayout-docker/files/7664806/after-python3.txt)

After installing make
[after-make.txt](https://github.com/ffplayout/ffplayout-docker/files/7664903/after-make.txt)

**Server (please complete the following information):**
 - OS: debian and ubuntu
 - Version: 10 and 21.10
 - Docker version 20.10.11, build dea9396 on Ubuntu
 - Docker version 20.10.11, build dea9396 on Debian

**Relase Version (please complete the following information):**
 - Version: [e.g. v3.0.0]

**Additional context**

**Comment by spencerhughes** [comment]
Sorry just noticed it was also mad about g++, adding that and building results in these logs:
[after-g++.txt](https://github.com/ffplayout/ffplayout-docker/files/7664940/after-g%2B%2B.txt)

**Comment by spencerhughes** [comment]
Tried replacing python3 with 2 and got a similar error. Thanks for looking into this, it looks like an awesome project :)

[python2.txt](https://github.com/ffplayout/ffplayout-docker/files/7693723/python2.txt)

**Comment by jb-alvarado** [comment]
I used the wrong images for the containers. The container definitions uses always the latest version from python and node.js and that is not good. The node container should use version 14, and the engine container should use python 3.9. I'm not done testing but I think that is enough.

**Comment by spencerhughes** [comment]
Updating those two docker images seems to have done the trick. I'll make a pull request with the changes :)

**Comment by jb-alvarado** [comment]
Finishes the install of the frontend by you? By me it hangs on the final step...

**Comment by spencerhughes** [comment]
Yeah it builds properly for me with those changes

**Comment by jb-alvarado** [comment]
Ok, thank you! I tried to, to update the ffplayout package version, and there it was hanging.
