### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by fabricioguedes** [ffplayout/ffplayout-docker#18]
ERROR: Service 'ffplayout-engine' failed to build: The command '/bin/sh -c cd /opt &&     wget "https://github.com/ffplayout/ffplayout-engine/archive/v${version}.zip" &&     unzip "v${version}.zip" &&     mv "ffplayout_engine-${version}" 'ffplayout-engine' &&     rm "v${version}.zip" &&     cd ffplayout-engine &&     pip install --no-cache-dir -r requirements-base.txt &&     mkdir /etc/ffplayout' returned a non-zero code: 1

Using docker, any dependencies?

**Comment by jb-alvarado** [comment]
The version was wrong.

Please have in mind, that the docker version is a bit outdated.
