### ISSUE TITLE
Unable to see playlist

### ISSUE THREAD

**Issue by lion01942** [ffplayout/ffplayout-docker#2]
First of all, thank you very much for the ffplayout repos. This saves a lot of time instead of building something from scratch.

After I bring up the service using "docker-compose up -d", I am able to pull up the UI (http://localhost:8088) and see the controls. Unfortunately, I was not able to see the playlist. I was wondering if I had to anything else as pre-requisites?
Note: There were no errors in the docker-compose up execution.

**Comment by jb-alvarado** [comment]
Have you check the composer config, if the path, for mounting, are exist on your machine?

**Comment by jb-alvarado** [comment]
Can you try this, on a fresh new **debian 10** machine?
- install [docker](https://linuxize.com/post/how-to-install-and-use-docker-on-debian-10/)
- install [docker compose](https://linuxize.com/post/how-to-install-and-use-docker-compose-on-debian-10/)
- create two folders: `mkdir /tv-media` and `mkdir /playlists`
- `cd /opt`
- clone ffplayout-docker repo, and build it
- login to GUI
- navigate to /media and upload a video file
- navigate to /player
- drag video file to playlist area and save playlist.

**Comment by lion01942** [comment]
> Can you try this, on a fresh new **debian 10** machine?
> 
> * install [docker](https://linuxize.com/post/how-to-install-and-use-docker-on-debian-10/)
> * install [docker compose](https://linuxize.com/post/how-to-install-and-use-docker-compose-on-debian-10/)
> * create two folders: `mkdir /tv-media` and `mkdir /playlists`
> * `cd /opt`
> * clone ffplayout-docker repo, and build it
> * login to GUI
> * navigate to /media and upload a video file
> * navigate to /player
> * drag video file to playlist area and save playlist.
> 
> I have done everything as root user.

I tried on a new Debian10 VM and followed all these steps. I could see the playlist (.json) with the media information, but I couldn't play via UI. 
Additionally, as per instruction in README (<Please use always the newest ffplayout.yml from engine, when you build everything new!>), I copied ffplayout.yml from ffplayout-engine repo into the ffplayout-docker repo. At this time, I could not see any files listed in the "Media" section.

**Comment by jb-alvarado** [comment]
In config > GUI the **player_url** must match, and When it still not working you need to check the different logs. For example it can happen that you have text overlay active, but the path to the font file is not correct.

**Comment by lion01942** [comment]
Thanks @jb-alvarado . Sorry for the delay in getting back. I think I had write limitation on the folder and hence engine was not able to generate output. The logs were not very clear. Anyway, I am glad to have resolved this.
