### ISSUE TITLE
media url is empty

### ISSUE THREAD

**Issue by ravibhushan29** [ffplayout/ffplayout-docker#3]
I am trying to access media file in front end but it is showing empty
<img width="1680" alt="Screenshot 1942-09-08 at 1 46 07 AM" src="https://user-images.githubusercontent.com/25654691/100525280-5350ad00-31e5-11eb-8fed-13b2a5127e32.png">
.

**Comment by jb-alvarado** [comment]
Are the paths in ffplayout.yaml config correct? and what says the browser log?
