### ISSUE TITLE
[Feature] Add SRT to FFmpeg 

### ISSUE THREAD

**Issue by cdavid14** [ffplayout/ffplayout-docker#4]
A sugestion around add SRT at ffplayout-engine dockerfile ffmpeg compiler

**Comment by jb-alvarado** [comment]
Yes that is a good idea! Can you add a PR?

**Comment by cdavid14** [comment]
Working on it! when done i'll add.

**Comment by jb-alvarado** [comment]
Cool, thank you!

**Comment by jengajenga** [comment]
Eagerly looking forward to SRT as well

**Comment by jb-alvarado** [comment]
Is done
