### ISSUE TITLE
Default Password

### ISSUE THREAD

**Issue by jengajenga** [ffplayout/ffplayout-docker#5]
Hello

Very very new to this. I'm happy  i found it.

Can someone tell me what the default password is? I've tried admin:admin but i get "Error: Request failed with status code 404"

Please assist.

Thank you

**Comment by jengajenga** [comment]
I tried to install on a second server, and the error i get is "TypeError: Cannot read property 'status' of undefined"

What am I doing wrong please?

Kindly help

Thank you again.

**Comment by jengajenga** [comment]
@jb-alvarado hello... are you there? could you kindly assist me?

thank you

**Comment by jb-alvarado** [comment]
Hi, 
the default credentials are admin:admin. I made the mistake to use the master branches from the given repos, and that break some things.

with the newest version you can login, but I think not everything is working at the moment. Is also hard to fix at the moment, because I'm working on a new version. When the new version is done I will fix the docker repo.

**Comment by jengajenga** [comment]
> Hi,
> the default credentials are **admin:admin**. I made the mistake to use the master branches from the given repos, and that break some things.
> 
> Try the latest master.

So i do a quick clean reinstall of this docker version? let me try.  I had tried using the non-dockerised version and i also got stuck.

I'll report back after installation.

**Comment by jengajenga** [comment]
Honestly I don't know what i'm doing wrong. I've edited docker-compose.yml as required. I've copied files in the config to the paths required. Still getting it wrong.

![pass](https://user-images.githubusercontent.com/65451390/104055724-4b325700-5200-11eb-99d2-f6972844e709.PNG)

Is it working for you? I have Ubuntu 20.04 LTS.

**Comment by jb-alvarado** [comment]
Try to just clone the docker repo and run **docker-compose up -d**, without a change in any config. Also clear your browser cache, when the error still comes, open the browser console, and past here the error message from there.

**Comment by jengajenga** [comment]
> Try to just clone the docker repo and run **docker-compose up -d**, without a change in any config. Also clear your browser cache, when the error still comes, open the browser console, and past here the error message from there.

alright. let me try that. i'll report back.

**Comment by jengajenga** [comment]
> Try to just clone the docker repo and run **docker-compose up -d**, without a change in any config. Also clear your browser cache, when the error still comes, open the browser console, and past here the error message from there.

well well, it has worked! thank you for this and for being very helpful.

now, i have another question but it is not related to installation so i will open another issue.

**Comment by jb-alvarado** [comment]
Good, that it works now!
