### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout-docker#7]
we tried the old install method with issues
then tried docker and the same.

is there an issue in the script that affects both ways of installing the system?

**Comment by jb-alvarado** [comment]
No the docker version don't use the install scrip and it also should work. [Here](https://github.com/ffplayout/ffplayout-docker/issues/5) was also a problem reported, but now it works.

**Comment by edwoodza** [comment]
We tried docker yesterday with no success
got this error on the compile
"error: for SRS cannot start srs service driver failed programing exteranl connectivity on endpoint to srs.....error starting userland proxy: listen tcp 0.0.0.0:1935: bind address already in use.

Can you send/post exact full docker instructions so we can be sure we did not screw something silly up

**Comment by jb-alvarado** [comment]
It look like that something on your system is already listening on port 1935. Try it on a fresh new system.

**Comment by edwoodza** [comment]
am unable to access GUI as well on port 8088 (unless port no changed) Port 80 returns 404 for nginx so webserver working.
install was a clean server using docker install nothing else so not sure what would be using port when its a clean Debian server

**Comment by jb-alvarado** [comment]
Are you using the debian docker packages version, or the the latest one from [docker.com](https://docs.docker.com/engine/install/debian/) with the newest **docker-composed**?

**Comment by edwoodza** [comment]
I will try check and revert re which ver
would it be possible to do a quick idiots guide to install with docker from scratch.
the help guide leaves room for massive mistakes.
this updated install guide would avoid many issue tickets as well it think

**Comment by jb-alvarado** [comment]
I working on a new install routine. But with docker there is really not much to do. You just follow the instruction from docker.com, install the latest docker-compose, go to /opt/, clone repo `git clone https://github.com/ffplayout/ffplayout-docker.git`, cd in repo and run `docker-compose up -d`.

After it is done, you can check if everything is running with: `docker ps`: Output should be like:

```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                                                                    NAMES
e75c64a6cad0   ffplayout-frontend:2.0   "/docker-entrypoint.…"   13 minutes ago   Up 13 minutes   0.0.0.0:8088->80/tcp                                                     ffplayout-frontend
339a89bb8902   ffplayout-api:2.0        "/start.sh"              13 minutes ago   Up 13 minutes   0.0.0.0:8001->8001/tcp                                                   ffplayout-api
b0674acfcb1a   ffplayout-engine:2.0     "/usr/local/bin/supe…"   13 minutes ago   Up 13 minutes   0.0.0.0:5555->5555/tcp, 0.0.0.0:64233->64233/tcp                         ffplayout-engine
e79a2e935e13   ossrs/srs:3              "./objs/srs -c conf/…"   13 minutes ago   Up 13 minutes   0.0.0.0:1935->1935/tcp, 0.0.0.0:1985->1985/tcp, 0.0.0.0:8087->8080/tcp   srs
```

**Comment by edwoodza** [comment]
Just successful installed on Ubuntu. Seems the 3 attempts on new Debian machines did not work
